name: music_flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  iconsax_flutter: ^1.0.0
  get_storage: ^2.1.1
  permission_handler: ^11.4.0
  on_audio_query: ^2.9.0
  gap: ^3.0.1
  device_info_plus: ^11.3.3
  just_audio: ^0.9.46
  flutter_sliding_up_panel: ^2.1.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets
